/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClipLabRouteImport } from './routes/clip-lab'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ClipLabCandidateIdRouteImport } from './routes/clip-lab.$candidateId'
import { Route as ProfilesProfileIdRouteImport } from './routes/profiles.$profileId'
import { Route as SourcesSourceIdRouteImport } from './routes/sources.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipLabRoute = ClipLabRouteImport.update({
  id: '/clip-lab',
  path: '/clip-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipLabCandidateIdRoute = ClipLabCandidateIdRouteImport.update({
  id: '/$candidateId',
  path: '/$candidateId',
  getParentRoute: () => ClipLabRoute,
} as any)
const ProfilesProfileIdRoute = ProfilesProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => ProfilesRoute,
} as any)
const SourcesSourceIdRoute = SourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => SourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/clip-lab': typeof ClipLabRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/profiles': typeof ProfilesRouteWithChildren
  '/queue': typeof QueueRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRouteWithChildren
  '/clip-lab/$candidateId': typeof ClipLabCandidateIdRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/clip-lab': typeof ClipLabRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/profiles': typeof ProfilesRouteWithChildren
  '/queue': typeof QueueRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRouteWithChildren
  '/clip-lab/$candidateId': typeof ClipLabCandidateIdRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/clip-lab': typeof ClipLabRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/profiles': typeof ProfilesRouteWithChildren
  '/queue': typeof QueueRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sources': typeof SourcesRouteWithChildren
  '/clip-lab/$candidateId': typeof ClipLabCandidateIdRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/sources/$sourceId': typeof SourcesSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/clip-lab'
    | '/dashboard'
    | '/library'
    | '/profiles'
    | '/queue'
    | '/robots.txt'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/sources'
    | '/clip-lab/$candidateId'
    | '/profiles/$profileId'
    | '/sources/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/clip-lab'
    | '/dashboard'
    | '/library'
    | '/profiles'
    | '/queue'
    | '/robots.txt'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/sources'
    | '/clip-lab/$candidateId'
    | '/profiles/$profileId'
    | '/sources/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/clip-lab'
    | '/dashboard'
    | '/library'
    | '/profiles'
    | '/queue'
    | '/robots.txt'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/sources'
    | '/clip-lab/$candidateId'
    | '/profiles/$profileId'
    | '/sources/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  ClipLabRoute: typeof ClipLabRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  ProfilesRoute: typeof ProfilesRouteWithChildren
  QueueRoute: typeof QueueRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourcesRoute: typeof SourcesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip-lab': {
      id: '/clip-lab'
      path: '/clip-lab'
      fullPath: '/clip-lab'
      preLoaderRoute: typeof ClipLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip-lab/$candidateId': {
      id: '/clip-lab/$candidateId'
      path: '/$candidateId'
      fullPath: '/clip-lab/$candidateId'
      preLoaderRoute: typeof ClipLabCandidateIdRouteImport
      parentRoute: typeof ClipLabRoute
    }
    '/profiles/$profileId': {
      id: '/profiles/$profileId'
      path: '/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof ProfilesProfileIdRouteImport
      parentRoute: typeof ProfilesRoute
    }
    '/sources/$sourceId': {
      id: '/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof SourcesSourceIdRouteImport
      parentRoute: typeof SourcesRoute
    }
  }
}

interface ClipLabRouteChildren {
  ClipLabCandidateIdRoute: typeof ClipLabCandidateIdRoute
}

const ClipLabRouteChildren: ClipLabRouteChildren = {
  ClipLabCandidateIdRoute: ClipLabCandidateIdRoute,
}

const ClipLabRouteWithChildren =
  ClipLabRoute._addFileChildren(ClipLabRouteChildren)

interface ProfilesRouteChildren {
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRoute
}

const ProfilesRouteChildren: ProfilesRouteChildren = {
  ProfilesProfileIdRoute: ProfilesProfileIdRoute,
}

const ProfilesRouteWithChildren = ProfilesRoute._addFileChildren(
  ProfilesRouteChildren,
)

interface SourcesRouteChildren {
  SourcesSourceIdRoute: typeof SourcesSourceIdRoute
}

const SourcesRouteChildren: SourcesRouteChildren = {
  SourcesSourceIdRoute: SourcesSourceIdRoute,
}

const SourcesRouteWithChildren =
  SourcesRoute._addFileChildren(SourcesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  ClipLabRoute: ClipLabRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  ProfilesRoute: ProfilesRouteWithChildren,
  QueueRoute: QueueRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourcesRoute: SourcesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
