"""Expand source fields for ingestion

Revision ID: c8acc0e51c14
Revises: 7e9a50d5b0f7
Create Date: 2026-07-21 22:27:37.247757
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c8acc0e51c14'
down_revision: Union[str, None] = '7e9a50d5b0f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source_kind', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('original_url', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('storage_key', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('extension', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('checksum_sha256', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('video_codec', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('audio_codec', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('audio_channels', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('audio_sample_rate', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('bitrate', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('container_format', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('inspection_status', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('inspection_error', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('thumbnail_storage_key', sa.String(), nullable=True))
    op.add_column('sources', sa.Column('inspected_at', sa.DateTime(), nullable=True))
    op.drop_column('sources', 'local_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('local_path', sa.VARCHAR(), nullable=True))
    op.drop_column('sources', 'inspected_at')
    op.drop_column('sources', 'thumbnail_storage_key')
    op.drop_column('sources', 'inspection_error')
    op.drop_column('sources', 'inspection_status')
    op.drop_column('sources', 'container_format')
    op.drop_column('sources', 'bitrate')
    op.drop_column('sources', 'audio_sample_rate')
    op.drop_column('sources', 'audio_channels')
    op.drop_column('sources', 'audio_codec')
    op.drop_column('sources', 'video_codec')
    op.drop_column('sources', 'checksum_sha256')
    op.drop_column('sources', 'extension')
    op.drop_column('sources', 'mime_type')
    op.drop_column('sources', 'storage_key')
    op.drop_column('sources', 'original_url')
    op.drop_column('sources', 'source_kind')
    # ### end Alembic commands ###